# Generated by Django 3.0.5 on 2025-10-15 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blood', '0004_bloodrequest_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bloodrequest',
            old_name='request_by_patient',
            new_name='patient',
        ),
    ]
